### PR TITLE
Make benchmarks fair

### PR DESCRIPTION
**Pull request by kelunik**
Previously the different implementations did different things during the
benchmark, such as Amp doing 50 jobs while other implementations did 20
or 30 jobs. Additionally, the concurrency limit has been adjusted to be
the same for all implementations.

For the second benchmark I added a second version based on Amp that uses
the event loop and non-blocking I/O like Guzzle instead of multiple
processes.

The third benchmark has been adjusted to purely use child processes
without any concurrency limit. I have removed the `spatie` benchmark
there, as there's no API to use fresh child processes there.

### CODE REVIEW

**Comment by brendt** [comment]
Very nice of you to take the time and PR this!

A few things I'd like to point out:

- The blogpost/repo benchmark only uses benchmark 3, as it represents the best use-case for what our package will be used. The other benchmarks are left in as they represent the things I tested, and can be used as a goal to improve our package in the future.
- The second goal for our package, which is equally important to us as performance; is developer friendliness. For us, that means that we should be comparing with the parallel functions package. As far as I know, React doesn't have a way of running closures or tasks the way Amp does. So the only reason I wanted to include React's benchmark was to have a baseline to compare against.

Regarding the iterations: it's an unfortunate mistake pushed to the repo during testing. I've immediately pushed a fix for this!

As you might remember, I opened an issue about Amp crashing during these benchmarks: https://github.com/amphp/parallel-functions/issues/5

To me the fairest comparison seems amp/parallel-functions against spatie/async, with the same amount of concurrency. It's my understanding that the issue I opened is now fixed, so I'll be able to redo the tests soon.

I'm not going to merge this PR right away, as I'd like to hear your feedback on the points above first. Also I'd like to mention, like in the blogpost is that spatie/async is not trying to compete with Amp, we're only trying to solve some use cases in another - to us better - way.

**Comment by kelunik** [comment]
I've just removed benchmark 3, as benchmark 1 does basically that now. I've also removed the `sleep`, as that only adds a delay, but we actually want to measure the overhead.

Including ReactPHP in the benchmark without it doing anything similar just gives a wrong picture. Of course it's faster to execute 50x `sleep(2)` in 50 processes compared to other implementations that use an upper limit for the number of concurrent workers. I have therefore removed ReactPHP entirely now.

Competition is entirely fine and drives innovation. Some packages might work better for some as others, but I think I (rightfully) question the results presented in the blog post.

**Comment by brendt** [comment]
Thanks for the input and spending time on this! I'll add your changes, and address the right results in the blogpost tomorrow.

**Comment by brendt** [comment]
However I feel that one benchmark is still missing, and would like your input. In real life situations; child processes are more likely to not finish at the same time. So I feel that the `sleep` test with random sleep times does need a comparison.

Though I'm not sure if `sleep` is the best way to run the benchmark. Ideally we'd like to compare higher CPU load, like eg. parsing and rendering files. Any suggestions on how you would approach this?

**Comment by brendt** [comment]
A question you made to benchmark 1:

I'm getting better Amp performance using this:

```php
$promises = parallelMap(range(1, 50), function ($i) {
    return true;
});

wait($promises);
```

Instead of wrapping it in a loop: average of 0.68s per iteration instead of 0.72s. Any reason why you're using the loop implementation instead?

**Comment by kelunik** [comment]
It makes the comparison fairer. The improved performance comes from only serializing the closure once instead of in each iteration.

Instead of / in addition to multiple iterations, it's probably better to adjust the benchmark to a variing number of jobs. Amp is significantly faster for 500 jobs, because it reuses the workers.

**Comment by kelunik** [comment]
Closing, as benchmarks have been refactored.

**Pull request closed without merging**
